-- Delete all FKs
-- while(exists(select 1 from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where CONSTRAINT_TYPE='FOREIGN KEY'))
-- begin
-- 	declare @sql nvarchar(2000)
-- 	SELECT TOP 1 @sql=('ALTER TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME
-- 	+ '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']')
-- 	FROM information_schema.table_constraints
-- 	WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
-- 	exec (@sql)
-- end


-- Delete all tables
-- EXEC sp_MSforeachtable @command1 = "DROP TABLE ?"





CREATE TABLE COUNTRIES
    (
     COUNTRY_ID VARCHAR(2)  NOT NULL ,
     COUNTRY_NAME VARCHAR(40) ,
     REGION_ID FLOAT
    )
;

CREATE UNIQUE INDEX COUNTRY_C_ID_PKX ON COUNTRIES
    (
     COUNTRY_ID ASC
    )
;

ALTER TABLE COUNTRIES
    ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY ( COUNTRY_ID ) ;





CREATE TABLE DEPARTMENTS
    (
     DEPARTMENT_ID SMALLINT   NOT NULL ,
     DEPARTMENT_NAME VARCHAR (30)  NOT NULL ,
     MANAGER_ID INT  ,
     LOCATION_ID SMALLINT
    )
;


CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS
    (
     LOCATION_ID ASC
    )
;

CREATE UNIQUE INDEX DEPT_ID_PKX ON DEPARTMENTS
    (
     DEPARTMENT_ID ASC
    )
;

ALTER TABLE DEPARTMENTS
    ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY ( DEPARTMENT_ID ) ;





CREATE TABLE EMPLOYEES
    (
     EMPLOYEE_ID INT   NOT NULL ,
     FIRST_NAME VARCHAR (20) ,
     LAST_NAME VARCHAR (25)  NOT NULL ,
     EMAIL VARCHAR (25)  NOT NULL ,
     PHONE_NUMBER VARCHAR (20) ,
     HIRE_DATE DATETIME  NOT NULL ,
     JOB_ID VARCHAR (10)  NOT NULL ,
     SALARY DECIMAL (8,2) ,
     COMMISSION_PCT DECIMAL (2,2) ,
     MANAGER_ID INT  ,
     DEPARTMENT_ID SMALLINT
    )
;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_SALARY_MIN
    CHECK ( salary > 0)
;

CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES
    (
     DEPARTMENT_ID ASC
    )
;

CREATE INDEX EMP_JOB_IX ON EMPLOYEES
    (
     JOB_ID ASC
    )
;

CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES
    (
     MANAGER_ID ASC
    )
;

CREATE INDEX EMP_NAME_IX ON EMPLOYEES
    (
     LAST_NAME ASC ,
     FIRST_NAME ASC
    )
;

CREATE UNIQUE INDEX EMP_EMP_ID_PKX ON EMPLOYEES
    (
     EMPLOYEE_ID ASC
    )
;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY ( EMPLOYEE_ID ) ;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_EMAIL_UK UNIQUE ( EMAIL ) ;





CREATE TABLE JOBS
    (
     JOB_ID VARCHAR (10)  NOT NULL ,
     JOB_TITLE VARCHAR (35)  NOT NULL ,
     MIN_SALARY INT  ,
     MAX_SALARY INT
    )
;

CREATE UNIQUE INDEX JOB_ID_PKX ON JOBS
    (
     JOB_ID ASC
    )
;

ALTER TABLE JOBS
    ADD CONSTRAINT JOB_ID_PK PRIMARY KEY ( JOB_ID ) ;





CREATE TABLE JOB_HISTORY
    (
     EMPLOYEE_ID INT   NOT NULL ,
     START_DATE DATETIME  NOT NULL ,
     END_DATE DATETIME  NOT NULL ,
     JOB_ID VARCHAR (10)  NOT NULL ,
     DEPARTMENT_ID SMALLINT
    )
;

ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT JHIST_DATE_CHECK
    CHECK (end_date > start_date)
;


CREATE INDEX JHIST_JOB_IX ON JOB_HISTORY
    (
     JOB_ID ASC
    )
;

CREATE INDEX JHIST_EMP_IX ON JOB_HISTORY
    (
     EMPLOYEE_ID ASC
    )
;

CREATE INDEX JHIST_DEPT_IX ON JOB_HISTORY
    (
     DEPARTMENT_ID ASC
    )
;

CREATE UNIQUE INDEX JHIST_ID_DATE_PKX ON JOB_HISTORY
    (
     EMPLOYEE_ID ASC ,
     START_DATE ASC
    )
;

ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT JHIST_ID_DATE_PK PRIMARY KEY ( EMPLOYEE_ID, START_DATE ) ;





CREATE TABLE LOCATIONS
    (
     LOCATION_ID SMALLINT   NOT NULL ,
     STREET_ADDRESS VARCHAR (40) ,
     POSTAL_CODE VARCHAR (12) ,
     CITY VARCHAR (30)  NOT NULL ,
     STATE_PROVINCE VARCHAR (25) ,
     COUNTRY_ID VARCHAR(2)
    )
;

CREATE INDEX LOC_CITY_IX ON LOCATIONS
    (
     CITY ASC
    )
;

CREATE INDEX LOC_STATE_PROV_IX ON LOCATIONS
    (
     STATE_PROVINCE ASC
    )
;

CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS
    (
     COUNTRY_ID ASC
    )
;

CREATE UNIQUE INDEX LOC_ID_PKX ON LOCATIONS
    (
     LOCATION_ID ASC
    )
;

ALTER TABLE LOCATIONS
    ADD CONSTRAINT LOC_ID_PK PRIMARY KEY ( LOCATION_ID ) ;





CREATE TABLE REGIONS
    (
     REGION_ID FLOAT  NOT NULL ,
     REGION_NAME VARCHAR (25)
    )
;

CREATE UNIQUE INDEX REG_ID_PKX ON REGIONS
    (
     REGION_ID ASC
    )
;

ALTER TABLE REGIONS
    ADD CONSTRAINT REG_ID_PK PRIMARY KEY ( REGION_ID ) ;

ALTER TABLE COUNTRIES
    ADD CONSTRAINT COUNTR_REG_FK FOREIGN KEY
    (
     REGION_ID
    )
    REFERENCES REGIONS
    (
     REGION_ID
    )
;

ALTER TABLE DEPARTMENTS
    ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY
    (
     LOCATION_ID
    )
    REFERENCES LOCATIONS
    (
     LOCATION_ID
    )
;

ALTER TABLE DEPARTMENTS
    ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY
    (
     MANAGER_ID
    )
    REFERENCES EMPLOYEES
    (
     EMPLOYEE_ID
    )
    -- NOT DEFERRABLE
;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY
    (
     DEPARTMENT_ID
    )
    REFERENCES DEPARTMENTS
    (
     DEPARTMENT_ID
    )
    -- NOT DEFERRABLE
;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY
    (
     JOB_ID
    )
    REFERENCES JOBS
    (
     JOB_ID
    )
    -- NOT DEFERRABLE
;

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY
    (
     MANAGER_ID
    )
    REFERENCES EMPLOYEES
    (
     EMPLOYEE_ID
    )
;

ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY
    (
     DEPARTMENT_ID
    )
    REFERENCES DEPARTMENTS
    (
     DEPARTMENT_ID
    )
;

ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY
    (
     EMPLOYEE_ID
    )
    REFERENCES EMPLOYEES
    (
     EMPLOYEE_ID
    )
;

ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT JHIST_JOB_FK FOREIGN KEY
    (
     JOB_ID
    )
    REFERENCES JOBS
    (
     JOB_ID
    )
;

ALTER TABLE LOCATIONS
    ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY
    (
     COUNTRY_ID
    )
    REFERENCES COUNTRIES
    (
     COUNTRY_ID
    )
;
